# Generated by Django 3.0.6 on 2023-05-12 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import proposta.propostas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta_Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ordem', models.CharField(default=proposta.propostas.models.nova_ordem2, max_length=20, unique=True, verbose_name='Número da proposta')),
                ('revisão', models.CharField(default='001', max_length=5, verbose_name='Revisão')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('Hora_extra', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, verbose_name='Horas extras')),
                ('Frete_ida', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('Frete_volta', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('Valor_Instalação', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('Condições_de_Pagamento', models.ForeignKey(default='1x sem juros', on_delete=django.db.models.deletion.CASCADE, related_name='propostas_grid', to='core.Condicao_Pagamento_Gerador')),
                ('Franquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_grid', to='core.Franquia_Gerador')),
                ('Operação', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_grid', to='core.Operacao_Gerador')),
                ('Prazo_da_Locação', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_grid', to='core.Locacao_Gerador')),
                ('Prazo_de_Entrega', models.ForeignKey(default='Sete', on_delete=django.db.models.deletion.CASCADE, related_name='propostas_grid', to='core.Prazo_Entrega')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_grid', to='core.Cliente')),
                ('garantia_gerador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propostas_grid', to='core.Garantia_Gerador')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propostas_grid', to=settings.AUTH_USER_MODEL)),
                ('validade', models.ForeignKey(default='Sete', on_delete=django.db.models.deletion.CASCADE, related_name='propostas_grid', to='core.Validade_Proposta')),
            ],
            options={
                'verbose_name': 'Proposta Grid',
                'verbose_name_plural': 'Propostas Grid',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Proposta_Brg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ordem', models.CharField(default=proposta.propostas.models.nova_ordem, max_length=200, unique=True, verbose_name='Número da proposta')),
                ('revisão', models.CharField(default='001', max_length=5, verbose_name='Revisão')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('Frete', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('Valor_Instalação', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('Condições_de_Pagamento', models.ForeignKey(default='1x sem juros', on_delete=django.db.models.deletion.CASCADE, related_name='proposta_brg', to='core.Condicao_Pagamento_Gerador')),
                ('Prazo_de_Entrega', models.ForeignKey(default='Sete', on_delete=django.db.models.deletion.CASCADE, related_name='proposta_brg', to='core.Prazo_Entrega')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposta_brg', to='core.Cliente')),
                ('garantia_gerador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Garantia_Gerador')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposta_brg', to=settings.AUTH_USER_MODEL)),
                ('validade', models.ForeignKey(default='Sete', on_delete=django.db.models.deletion.CASCADE, related_name='proposta_brg', to='core.Validade_Proposta')),
            ],
            options={
                'verbose_name': 'Proposta BRG',
                'verbose_name_plural': 'Propostas BRG',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Proposta_Agrogera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ordem', models.CharField(default=proposta.propostas.models.nova_ordem3, max_length=20, unique=True, verbose_name='Número da proposta')),
                ('revisão', models.CharField(default='001', max_length=5, verbose_name='Revisão')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('Hora_extra', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, verbose_name='Horas extras')),
                ('Frete_ida', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('Frete_volta', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('Valor_Instalação', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('Condições_de_Pagamento', models.ForeignKey(default='1x sem juros', on_delete=django.db.models.deletion.CASCADE, related_name='propostas_agrogera', to='core.Condicao_Pagamento_Gerador')),
                ('Franquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_agrogera', to='core.Franquia_Gerador')),
                ('Operação', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_agrogera', to='core.Operacao_Gerador')),
                ('Prazo_da_Locação', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_agrogera', to='core.Locacao_Gerador')),
                ('Prazo_de_Entrega', models.ForeignKey(default='Sete', on_delete=django.db.models.deletion.CASCADE, related_name='propostas_agrogera', to='core.Prazo_Entrega')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_agrogera', to='core.Cliente')),
                ('garantia_gerador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propostas_agrogera', to='core.Garantia_Gerador')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propostas_agrogera', to=settings.AUTH_USER_MODEL)),
                ('validade', models.ForeignKey(default='Sete', on_delete=django.db.models.deletion.CASCADE, related_name='propostas_agrogera', to='core.Validade_Proposta')),
            ],
            options={
                'verbose_name': 'Proposta AgroGera',
                'verbose_name_plural': 'Propostas AgroGera',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='produto_proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalizar_nome', models.CharField(blank=True, max_length=100, verbose_name='Adicionar descrição')),
                ('quantidade_Gerador', models.DecimalField(blank=True, decimal_places=0, default='1', max_digits=15)),
                ('valor_gerador', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=15, null=True)),
                ('Observacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observação')),
                ('Controlador_Gerador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Controlador_gerador')),
                ('Desconto', models.ForeignKey(default='0%', on_delete=django.db.models.deletion.CASCADE, to='core.Desconto')),
                ('Nivel_de_ruído', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Nivel_Ruido')),
                ('QTA_Gerador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Qta_Gerador')),
                ('Tensão_Gerador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tensao_Gerador')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Motor')),
                ('proposta_Agrogera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propostas_agrogera', to='propostas.Proposta_Agrogera')),
                ('proposta_Brg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propostas_brg', to='propostas.Proposta_Brg')),
                ('proposta_Grid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propostas_grid', to='propostas.Proposta_Grid')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-produto__Modelo_Gerador'],
            },
        ),
        migrations.CreateModel(
            name='Personalizar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, upload_to='produtos/personalizar')),
                ('Observacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observação')),
                ('proposta_Agrogera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalizar_propostas_agrogera', to='propostas.Proposta_Agrogera')),
                ('proposta_Brg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalizar_propostas_brg', to='propostas.Proposta_Brg')),
                ('proposta_Grid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalizar_propostas_grid', to='propostas.Proposta_Grid')),
            ],
            options={
                'verbose_name': 'Personalizações',
                'verbose_name_plural': 'Personalizações',
            },
        ),
        migrations.CreateModel(
            name='Acessorio_propostas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Observacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observação')),
                ('quantidade_acessorio', models.DecimalField(blank=True, decimal_places=0, default='1', max_digits=15, verbose_name='Quantidade Acessório')),
                ('valor_acessorio', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=15, null=True, verbose_name='Valor Acessório')),
                ('acessorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Acessorio')),
                ('proposta_Agrogera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acessorio_propostas_agrogera', to='propostas.Proposta_Agrogera')),
                ('proposta_Brg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acessorio_propostas_brg', to='propostas.Proposta_Brg')),
                ('proposta_Grid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acessorio_propostas_grid', to='propostas.Proposta_Grid')),
            ],
            options={
                'verbose_name': 'Acessórios Proposta',
                'verbose_name_plural': 'Acessório Proposta',
            },
        ),
    ]
