# Generated by Django 3.0.6 on 2023-05-12 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_produto_produto'),
        ('propostas', '0002_auto_20230512_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto_proposta',
            options={'ordering': ['-produto__Modelo_Gerador'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='produto_proposta',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Motor'),
        ),
    ]
