# Generated by Django 3.0.6 on 2023-05-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='produto',
        ),
    ]
