# Generated by Django 3.0.6 on 2023-05-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0003_auto_20230512_1348'),
        ('core', '0003_remove_produto_produto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
