# Generated by Django 3.0.6 on 2023-05-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='Modelo_Gerador',
            field=models.CharField(max_length=100, verbose_name='Grupo Gerador'),
        ),
    ]
