# Generated by Django 3.0.6 on 2023-05-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230515_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motor',
            options={'ordering': ['Modelo_Gerador'], 'verbose_name': 'Especificações Gerador', 'verbose_name_plural': 'Especificações Gerador'},
        ),
    ]
